// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VnStockproxx.Models;

#nullable disable

namespace VnStockproxx.Migrations
{
    [DbContext(typeof(VnStockproxxDbContext))]
    [Migration("20240610143347_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VnStockproxx.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("categoryName")
                        .UseCollation("Vietnamese_CI_AS");

                    b.HasKey("Id");

                    b.ToTable("Category", (string)null);
                });

            modelBuilder.Entity("VnStockproxx.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CateId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasMaxLength(299)
                        .HasColumnType("nvarchar(299)")
                        .HasColumnName("content")
                        .UseCollation("Vietnamese_CI_AS");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("createdDate")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(299)
                        .HasColumnType("nvarchar(299)");

                    b.Property<string>("Teaser")
                        .HasMaxLength(299)
                        .HasColumnType("nvarchar(299)")
                        .HasColumnName("teaser")
                        .UseCollation("Vietnamese_CI_AS");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("title")
                        .UseCollation("Vietnamese_CI_AS");

                    b.Property<DateTime?>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updatedDate")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("ViewCount")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("viewCount");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CateId" }, "IX_Post_CateId");

                    b.ToTable("Post", null, t =>
                        {
                            t.HasTrigger("Post_ForUpdate");

                            t.HasTrigger("trg_UpdateUpdatedDate");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("VnStockproxx.Models.Post", b =>
                {
                    b.HasOne("VnStockproxx.Models.Category", "Cate")
                        .WithMany("Posts")
                        .HasForeignKey("CateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Post_Category");

                    b.Navigation("Cate");
                });

            modelBuilder.Entity("VnStockproxx.Models.Category", b =>
                {
                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
